apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-info-deployment
  labels:
    app: request-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-info
  template:
    metadata:
      labels:
        app: request-info
    spec:
      containers:
      - name: request-info
        image: renukafernando/request-info:latest
        ports:
        - name: rest-api
          containerPort: 8080
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: request-info-service
spec:
  selector:
    app: request-info
  ports:
    - name: rest-api
      protocol: TCP
      port: 80
      targetPort: rest-api
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-ingress
spec:
  rules:
  - http:
      paths:
      - path: /req-info
        pathType: Prefix
        backend:
          service:
            name: request-info-service
            port:
              name: rest-api
